-- +goose Up
-- +goose StatementBegin

-- user_avatars (boom-9v4): per-user AI-generated CHIBI portrait rendered
-- via the ComfyUI shim from an LLM-authored prompt derived from the user's
-- top labels + activity synopsis. One row per user (PK on username), lazy-
-- populated when the user hits the Settings > Avatar tab and clicks
-- RENDER — nothing is generated at signup or on any background schedule.
--
-- Nullable image_bytes because the row is inserted with status='running'
-- BEFORE the shim call returns (5-25 min on chroma-hd). Status transitions:
--
--   pending  → initial reservation (no shim call yet)
--   running  → shim call in flight
--   ready    → image_bytes populated; usable
--   error    → shim/DB failure; error_message set; caller can retry
--
-- prompt/model/seed are provenance: the FINAL prompt sent to the shim (LLM
-- authored + user edited), the shim pipeline used, and the resolved seed if
-- the shim reported one. Used by the ops workflow for reproducibility.
--
-- Public read served by GET /api/v1/users/:username/avatar with a modest
-- Cache-Control (30s, not immutable) — unlike shared label archetype
-- images, a user re-renders their avatar iteratively during onboarding
-- and the freshly-generated bytes need to propagate promptly. FE can
-- optionally cache-bust via ?v=<updated_at.epoch> when it holds the value.

CREATE TABLE public.user_avatars (
    username        TEXT PRIMARY KEY REFERENCES public.users(username) ON DELETE CASCADE,
    image_bytes     BYTEA,
    mime_type       TEXT NOT NULL DEFAULT 'image/png',
    prompt          TEXT,
    model           TEXT,
    seed            BIGINT,
    status          TEXT NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending','running','ready','error')),
    error_message   TEXT,
    generated_at    TIMESTAMPTZ,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX user_avatars_status_idx ON public.user_avatars (status);

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS public.user_avatars;
-- +goose StatementEnd
