#!/usr/bin/env python3
"""Fetch + summarize the Hardcover GraphQL schema (introspection).

Token source (first that resolves):
  1. --token <t>
  2. HARDCOVER_TOKEN env
  3. --token-file <path>   (e.g. a scratch file with the raw token)
The token is defensively de-quoted (Hardcover stores it JSON-encoded, so a raw
grab looks like  "eyJ..."  — sending that verbatim yields a 401 "Unable to verify
token"; we strip the surrounding quotes + whitespace).

Usage:
  HARDCOVER_TOKEN=eyJ... scripts/hardcover_schema.py --out hardcover-schema.json
  task hardcover:schema-inspect            # (wraps this)

Writes the full introspection JSON to --out and prints a summary of the reading-
domain types (user_books, user_book_reads, editions, books, book_series, series,
authors, tags). Add --md <path> to also write a distilled markdown reference.
"""
import argparse
import json
import os
import sys
import urllib.request
import urllib.error

ENDPOINT = "https://api.hardcover.app/v1/graphql"

INTROSPECTION = """query IntrospectionQuery {
  __schema { queryType { name }
    types { kind name description
      fields(includeDeprecated:true){ name args{ name type{ ...T } } type{ ...T } }
      inputFields{ name type{ ...T } }
      enumValues(includeDeprecated:true){ name }
    } } }
fragment T on __Type { kind name ofType{ kind name ofType{ kind name ofType{ kind name ofType{ kind name } } } } }"""

# The reading-domain types worth surfacing in the summary + markdown.
READING_TYPES = [
    "user_books", "user_book_reads", "editions", "books",
    "book_series", "series", "contributions", "authors",
    "taggings", "tags", "book_categories", "book_statuses",
]


def resolve_token(args) -> str:
    tok = args.token or os.environ.get("HARDCOVER_TOKEN")
    if not tok and args.token_file:
        with open(args.token_file) as f:
            tok = f.read()
    if not tok:
        sys.exit("no token: pass --token, set HARDCOVER_TOKEN, or use --token-file")
    tok = tok.strip()
    # Hardcover stores the token JSON-encoded; a bare grab is quoted. De-quote it.
    if len(tok) >= 2 and tok[0] == '"' and tok[-1] == '"':
        try:
            tok = json.loads(tok)
        except Exception:
            tok = tok[1:-1]
    return tok.strip()


def fetch(tok: str) -> dict:
    body = json.dumps({"query": INTROSPECTION}).encode()
    req = urllib.request.Request(
        ENDPOINT, body,
        {"Content-Type": "application/json", "Authorization": "Bearer " + tok},
    )
    try:
        with urllib.request.urlopen(req, timeout=60) as r:
            return json.loads(r.read())
    except urllib.error.HTTPError as e:
        sys.exit(f"introspection failed: HTTP {e.code} {e.read().decode()[:200]}")


def unwrap(tp: dict) -> str:
    n = tp.get("name")
    o = tp.get("ofType")
    while not n and o:
        n = o.get("name")
        o = o.get("ofType")
    return n or "?"


def main() -> None:
    ap = argparse.ArgumentParser(description="Fetch + summarize the Hardcover GraphQL schema.")
    ap.add_argument("--token")
    ap.add_argument("--token-file")
    ap.add_argument("--out", default="hardcover-schema.json", help="full introspection JSON output")
    ap.add_argument("--md", help="also write a distilled markdown reference of the reading types")
    args = ap.parse_args()

    tok = resolve_token(args)
    d = fetch(tok)
    if "errors" in d:
        sys.exit("introspection returned errors: " + json.dumps(d["errors"])[:200])
    with open(args.out, "w") as f:
        json.dump(d, f)
    types = {t["name"]: t for t in d["data"]["__schema"]["types"] if t.get("name")}
    print(f"# Hardcover schema: {len(types)} types → {args.out}")

    md = ["# Hardcover GraphQL schema — reading domain (generated by scripts/hardcover_schema.py)\n"]
    for tn in READING_TYPES:
        t = types.get(tn)
        if not t:
            print(f"\n## {tn}: (absent)")
            continue
        fs = t.get("fields") or []
        line = ", ".join(f"{f['name']}:{unwrap(f['type'])}" for f in fs)
        print(f"\n## {tn} ({len(fs)} fields)\n  {line[:400]}")
        md.append(f"## {tn} ({len(fs)} fields)\n\n" + "\n".join(f"- `{f['name']}`: {unwrap(f['type'])}" for f in fs) + "\n")
    if args.md:
        with open(args.md, "w") as f:
            f.write("\n".join(md))
        print(f"\n# wrote distilled reference → {args.md}")


if __name__ == "__main__":
    main()
