---
apiVersion: v1
kind: Service
metadata:
  name: boomtime
  labels:
    app: boomtime
    app.kubernetes.io/name: boomtime
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
  selector:
    app: boomtime
